config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  root 'welcome#index'

  get 'welcome/index'

  resources :items do
    resources :bids
    collection do
      get 'filter_by_tags'
    end
  end

  resource :items_csv, only: %i[new create], controller: 'items_csv' do
    post :preview, on: :member
  end

  resource :site_settings, only: %i[show update]
  get 'site_disabled', to: 'site_disabled#index'

  resources :awards, only: %i[index create] do
    get ':filename', action: :download, on: :collection, as: :download, constraints: { filename: %r{[^/]+} }
    delete ':filename', action: :destroy, on: :collection, as: :delete, constraints: { filename: %r{[^/]+} }
  end

  resources :users
  resources :tags

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :bids, dependent: :destroy
  has_many :items, through: :bids
  validates :code, presence: true
  validates :code, uniqueness: true
  validates :name, presence: true
  default_scope { order(name: :asc) }
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_admin!, except: %i[index show]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    params[:user][:code] = params[:user][:code].downcase.strip
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new, status: :unprocessable_content
    end
  end

  def update
    params[:user][:code] = params[:user][:code].downcase.strip
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to root_path, status: :see_other
  end

  private

  def user_params
    params.expect(user: %i[code name balance])
  end
end

app/helpers/user_helper.rb
# frozen_string_literal: true

module UserHelper
end

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div class="mt-3">
    <%= form.label :code %><br>
    <%= form.text_field :code %>
    <% user.errors.full_messages_for(:code).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mt-3">
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% user.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div class="mt-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= render "tabs", tab: "user" %>

<h1>Edit User</h1>

<%= render "form", user: @user %>

<%= link_to "Destroy", user_path(@user),
    class: "btn btn-default bg-danger-subtle mt-3" ,
    data: {
            turbo_method: :delete,
            turbo_confirm: "Are you sure?"
          } %>

app/views/users/index.html.erb
<%= render "tabs", tab: "user" %>

<% if admin_signed_in? %>
  <p>
    <%= link_to "New User", new_user_path,
        { class: "btn btn-default bg-danger-subtle" } %>
  </p>
<% end %>
<br/>
Click a person's name to see their activity
<% @users.each do |user| %>
  <hr>
  <div class="panel panel-default p-1 mt-4">
    <%= link_to(user.name, user_path(user),
              { class: "btn btn-default btn-lg bg-info-subtle" }) %>
    Balance: <%= user.balance %>
  </div>
<% end %>

app/views/users/new.html.erb
<%= render "tabs", tab: "user" %>

<h1>New User</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<%= render "tabs", tab: "user" %>

<h1><%= @user.name %></h1>

<p>
  Balance: <%= @user.balance %>
  <% if admin_signed_in? %>
    <br/>Code: <%= @user.code %>
  <% end %>
</p>

<% if admin_signed_in? %>
  <div class="container p-2">
    <%= link_to "Edit User", edit_user_path(@user),
        { class: "btn btn-default bg-danger-subtle" } %>
  </div>
<% end %>

<h2>Bids</h2>
<% @user.bids.includes(:item).order("items.title").each do |bid| %>
  <hr>
  <%= link_to(bid.item.title, item_path(bid.item),
              { class: "btn btn-default btn-lg bg-info-subtle" }) %>
  Hearts: <%= bid.amount %>
  <% if bid.item.cost %>
    (<%= bid.amount / bid.item.cost %> count)
  <% end %>
<% end %>