config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  root 'welcome#index'

  get 'welcome/index'

  resources :items do
    resources :bids
    collection do
      get 'filter_by_tags'
    end
  end

  resource :items_csv, only: %i[new create], controller: 'items_csv' do
    post :preview, on: :member
  end

  resource :site_settings, only: %i[show update]
  get 'site_disabled', to: 'site_disabled#index'

  resources :awards, only: %i[index create] do
    get ':filename', action: :download, on: :collection, as: :download, constraints: { filename: %r{[^/]+} }
    delete ':filename', action: :destroy, on: :collection, as: :delete, constraints: { filename: %r{[^/]+} }
  end

  resources :users
  resources :tags

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/welcome/index.html.erb
<%= render "tabs", tab: "home" %>

<% if admin_signed_in? %>
  <p class="mt-3">
    <%= link_to "New Item", new_item_path,
        { class: "btn btn-default bg-danger-subtle" } %>
    <%= link_to "Upload CSV", new_items_csv_path,
        { class: "btn btn-default bg-danger-subtle" } %>
    <%= link_to "New User", new_user_path,
        { class: "btn btn-default bg-danger-subtle" } %>
    <%= link_to "Site Settings", site_settings_path,
        { class: "btn btn-default bg-danger-subtle" } %>
    <%= link_to "Award", awards_path,
        { class: "btn btn-default bg-danger-subtle" } %>
  </p>
<% end %>

<br/>

<p>
  As a participant in the auction, you have 500 hearts to use between
  raffle and auction items. Each type of item works differently:
</p>

<p>
  <b><a href="/items?type=Raffle">Raffle Items:</a></b>
  Choose how many hearts you would like to enter for each item. Many
  items have multiple winners. Raffle winners will be drawn after the
  event has concluded and notified via email.
</p>

<p>
  Note: Some raffle items are "unlimited." This means that they cost 1
  heart and have no participation limit. If you enter a heart for
  one of these items, you are guaranteed a spot at the event for you
  and a plus one, or you and your family.
</p>

<p>
  <b><a href="/items?type=Auction">Auction:</a></b>
  These items will be auctioned live during the event (see details
  below). You can view the item listings before the auction starts.
</p>

<br/>

<p>
  <h4>Website Navigation:</h4>
</p>

<p>
  <b>To view items</b>, select the corresponding tab at the top of the
  page. For raffle items, click Filter by Tag to see only items
  falling into a particular category.
</p>

<p>
  <b>To view item details</b>, including item description, host,
  accessibility information, and timing, select the Enter Hearts
  button to the right of an item.
</p>

<p>
  <b>To enter hearts</b>, write in <b>your unique code</b> and
  the number of hearts you want to enter. This number will be
  deducted from your total. <b>To change the number of hearts</b> you
  want for a certain item, type in your code and the <b>total number
  of hearts</b> you want, then click the "Update Hearts"
  button. (For example, if you have already entered 10 hearts, and
  you want to add 5 more, type in 15 total. If you type in 5, you will
  only enter 5.)  If you want to remove all of your hearts from an
  item, type in your code, enter 0 hearts, and click "Update
  Hearts."
</p>

<p>
  Note: For <b>raffle items that are unlimited</b>, type in your code,
  check the "Get One" box, and click "Update Hearts." Each unlimited
  item costs 1 heart. This number will be deducted from your
  total. To remove yourself from an unlimited item, type in your code,
  un-check the "Get One" box, and click "Update Hearts."
</p>

<p>
  <b>To view your heart balance</b>, select the Users tab and find
  your name. <b>Click on your name</b> to see how many hearts you
  have spent on each item.
</p>

<br/>

<h4>Auction:</h4>
<p>
  During the auction, each item will be announced, and you will have a
  chance to bid. The item will go to the highest individual bidder,
  who will have deducted the number of hearts they bid. The amount you
  bid is part of your total heart count. Please do not bid more than
  you have.
</p>

<p>
  After the auction, there will be a chance to enter any hearts not
  used in the auction on UNLIMITED raffle items. Most of the raffle
  items will be unavailable for bidding after 3 pm.
</p>

<p>
  Thank you for your participation! We could not do the work we do
  without your support.
</p>

<h4>Raffle Drawing Strategy</h4>

<p>
  In keeping with the anti-capitalist, community-centered spirit of
  this event, we are using a modified approach to drawing raffle
  winners. You can read more about our algorithm below, but the short
  version is: we’re making it more likely that everyone who
  participates will win something! To increase your chances of winning
  the items you want, we suggest using the following strategy:
</p>

<ul>
  <li>Put at least 1 heart on every item you are interested in.</li>

  <li>
    Put the most hearts on the item you are most interested in. Then,
    put the second-most hearts on the item you are second-most
    interested in, and so on. (For example: If you have 100 hearts
    and are interested in 3 items, you might put 50 hearts on your
    first choice, 30 on your second choice, and 20 on your third
    choice.)
  </li>
</ul>

<p>
  One way to do this is to start by going through the list of raffle
  items and adding 1 heart to every item you are interested in. Then,
  look at the list of items you have put hearts on, and add more to
  your favorites until all your remaining hearts are distributed.
</p>

<h4>The Algorithm</h4>
<p>
  To maximize the chances of everyone winning at least one item they
  are interested in, we are using an algorithm to choose winners
  rather than doing a simple random heart draw. The algorithm works
  in the following way:
</p>
<ul>
  <li>One participant is randomly selected.<sup>*</sup></li>
  <li>The selected participant is assigned the item that they placed the most hearts on.</li>
    <ul>
      <li>If that item is no longer available, they are assigned the item they placed the second-most hearts on, and so on.</li>
      <li>
	If they placed the same number of hearts on two items, they are assigned whichever item has the fewest total hearts from
	all participants.
      </li>
    </ul>
  <li>
    The process repeats until all items are assigned or there are no
    participants left who want the remaining items.
  </li>
</ul>

<sup>*</sup>Note: the random selection is technically a shuffle of
all the participants, so no one gets two items before everyone has at
least had a chance to get their first time.  Once everyone gets a
chance to get something, the list of participants is again shuffled.