config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admins
  root 'welcome#index'

  get 'welcome/index'

  resources :items do
    resources :bids
    collection do
      get 'filter_by_tags'
    end
  end

  resource :items_csv, only: %i[new create], controller: 'items_csv' do
    post :preview, on: :member
  end

  resource :site_settings, only: %i[show update]
  get 'site_disabled', to: 'site_disabled#index'

  resources :awards, only: %i[index create] do
    get ':filename', action: :download, on: :collection, as: :download, constraints: { filename: %r{[^/]+} }
    delete ':filename', action: :destroy, on: :collection, as: :delete, constraints: { filename: %r{[^/]+} }
  end

  resources :users
  resources :tags

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :item_tags, dependent: :destroy
  has_many :items, through: :item_tags

  validates :name, presence: true, uniqueness: true
  default_scope { order(group: :asc, name: :asc) }
  scope :order_by_group, -> { reorder(group: :asc) }

  def self.groups
    order_by_group.distinct.pluck(:group)
  end
end

app/controllers/tags_controller.rb
# frozen_string_literal: true

class TagsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end

  def new
    @tag = Tag.new
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def create
    @tag = Tag.new(tag_params)

    if @tag.save
      flash.notice = "#{@tag.name} tag created."
      redirect_to tags_url
    else
      render :new, status: :unprocessable_content
    end
  end

  def update
    @tag = Tag.find(params[:id])

    if @tag.update(tag_params)
      flash.notice = 'Tag was successfully updated.'
      redirect_to tags_url
    else
      render :edit, status: :unprocessable_content
    end
  end

  def destroy
    @tag = Tag.find(params[:id])
    name = @tag.name
    @tag.destroy
    flash.notice = "#{name} tag successfully destroyed."

    redirect_to tags_url
  end

  private

  def tag_params
    params.expect(tag: %i[group name])
  end

  def authenticate_admin!
    return if admin_signed_in?

    redirect_to root_path, alert: I18n.t('must_be_admin')
  end
end

app/helpers/tags_helper.rb
# frozen_string_literal: true

module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_with model: tag do |form| %>
  <div class="mt-3">
    <%= form.label :group %><br>
    <%= form.text_field :group, size: 60 %>
    <% tag.errors.full_messages_for(:group).each do |message| %>
      <div class="error"><%= message %></div>
    <% end %>
  </div>
  <div class="mt-3">
    <%= form.label :name %><br>
    <%= form.text_field :name, size: 60 %>
    <% tag.errors.full_messages_for(:name).each do |message| %>
      <div class="error"><%= message %></div>
    <% end %>
  </div>

  <div class="mt-3">
    <%= form.submit %>
  </div>
<% end %>

app/views/tags/create.html.erb
<h1>Tags#create</h1>
<p>Find me in app/views/tags/create.html.erb</p>

app/views/tags/destroy.html.erb
<h1>Tags#destroy</h1>
<p>Find me in app/views/tags/destroy.html.erb</p>

app/views/tags/edit.html.erb
<%= render "tabs", tab: "tags" %>

<h1 class="mt-4">Edit Tag</h1>

<%= render "form", tag: @tag %>

<%= link_to "Destroy", tag_path(@tag),
    class: "btn btn-default bg-danger-subtle mt-3" ,
    data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"
    } %>

app/views/tags/index.html.erb
<%= render "tabs", tab: "tags" %>

<h1>All Tags</h1>
<% if admin_signed_in? %>
  <p>
    <%= link_to "New Tag", new_tag_path,
        { class: "btn btn-default bg-danger-subtle" } %>
  </p>
  <hr>
<% end %>

<div class="container">
  <div class="row">
    <% Tag.groups.each do |group| %>
      <div class="col-md-4 col-sm-12 mb-3">
        <h4><%= group if group %></h4>
        <% @tags.where(group: group).each do |tag| %>
          <div class="panel panel-default p-1">
            <div class="row">
              <div class="col">
                <%= link_to(tag.name, edit_tag_path(tag),
                    { class: "mb-2 btn btn-default btn-lg bg-info-subtle" }) %><br/>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/tags/new.html.erb
<%= render "tabs", tab: "tags" %>

<h1>New Tag</h1>

<%= render "form", tag: @tag %>

app/views/tags/show.html.erb
<h1><%= @tag.group %>: <%= @tag.name %> Tag</h1>

app/views/tags/update.html.erb
<h1>Tags#update</h1>
<p>Find me in app/views/tags/update.html.erb</p>